os: linux
dist: xenial

language: java
jdk:
  - openjdk8
  - openjdk11
arch:
  - amd64
  - arm64

jobs:
  include:

    - os: osx
      language: java
      osx_image: xcode9
      script: mvn clean test

    - os: windows
      language: shell
      before_install:
        - |-
          export JAVA_HOME=${JAVA_HOME:-/c/jdk}
          export MAVEN_HOME=${MAVEN_HOME:-/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3}
          export PATH=${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}
          choco install jdk8 -params 'installdir=c:\\jdk' -y
          choco install maven --version 3.6.3 -y
          java -version
          echo $MAVEN_HOME
          ls $MAVEN_HOME
          echo $MAVEN_HOME/bin
          ls $MAVEN_HOME/bin
          mvn -version

      script: mvn clean test

install: true